name: Run

on:
  workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to deploy'
          type: environment
          required: true
          
jobs:
  build_jar:
    environment:
      name: "Production"
    name: Build jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name:  Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
            name: EmailService-0.0.1-SNAPSHOT.jar
            path: ${{ github.workspace }}/target/EmailService-0.0.1-SNAPSHOT.jar
